[RI 68] - Botón comprar producto
jvegax/Acme-Padel pull request #70
Opened 2022-12-01 15:52 UTC by jonatep

2022-12-01 16:28 UTC, jvegax requested changes

2022-12-01 16:28 UTC, jvegax commented on static/js/cart.js
> +  window.location.replace("http://127.0.0.1:8000/checkout?buyNow=yes");
Elimina la ruta absoluta `http://127.0.0.1:8000` 
Esto solo te va a funcionar en local, pero nunca en un entorno de producción

2022-12-01 16:28 UTC, jvegax commented on pedidos/views.py
> +            return 0 #Si la peticion era para comprar un producto inmediato, hay que eliminarlo del localStorage y carrito
Eliminar `?buyNow=Yes` de la ruta y cambiarlo por una nueva ruta `/checkout/buynow`

2022-12-01 16:42 UTC, jonatep commented on static/js/cart.js
> +  window.location.replace("http://127.0.0.1:8000/checkout?buyNow=yes");
Listo, ya está cambiado en el último commit

2022-12-01 16:42 UTC, jonatep commented on pedidos/views.py
> +            return 0 #Si la peticion era para comprar un producto inmediato, hay que eliminarlo del localStorage y carrito
Listo, ya está cambiado en el último commit

2022-12-04 16:14 UTC, josmarlop16 approved these changes

2022-12-04 16:14 UTC, josmarlop16 approved these changes

2022-12-06 10:22 UTC, jvegax approved these changes

2022-12-06 10:22 UTC, merged